In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv("../data/insider_threat_clean_dataset.csv")
df.head()

,employee_department,employee_campus,employee_position,employee_seniority_years,is_contractor,employee_classification,has_foreign_citizenship,has_criminal_record,has_medical_history,employee_origin_country,...,total_files_burned,burned_from_other,is_abroad,trip_day_number,hostility_country_level,num_entries,num_unique_campus,late_exit_flag,entry_during_weekend,is_malicious
0,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,4,0,0,0.0,0,1,1,0,1,0
1,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
2,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,2,0,0,0.0,0,1,1,0,0,0
3,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,1,1,0,0,0
4,Engineering Department,Campus C,Design Engineer,22,0,2,0,0,0,Georgia,...,0,0,0,0.0,0,0,0,0,0,0

In [2]:
df.shape

(118614, 22)

In [3]:
df.dtypes

employee_department             object
employee_campus                 object
employee_position               object
employee_seniority_years         int64
is_contractor                    int64
employee_classification          int64
has_foreign_citizenship          int64
has_criminal_record              int64
has_medical_history              int64
employee_origin_country         object
total_printed_pages              int64
num_printed_pages_off_hours      int64
total_files_burned               int64
burned_from_other                int64
is_abroad                        int64
trip_day_number                float64
hostility_country_level          int64
num_entries                      int64
num_unique_campus                int64
late_exit_flag                   int64
entry_during_weekend             int64
is_malicious                     int64
dtype: object

In [4]:
df.describe()

,employee_seniority_years,is_contractor,employee_classification,has_foreign_citizenship,has_criminal_record,has_medical_history,total_printed_pages,num_printed_pages_off_hours,total_files_burned,burned_from_other,is_abroad,trip_day_number,hostility_country_level,num_entries,num_unique_campus,late_exit_flag,entry_during_weekend,is_malicious
count,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.000000,118614.0,118614.00000,118614.000000
mean,12.371508,0.140616,1.889743,0.163168,0.049311,0.151340,13.708458,0.583894,9.380815,0.007234,0.041825,0.223397,0.005564,0.746261,0.597948,0.0,0.05061,0.053839
std,7.195372,0.347626,0.749889,0.369520,0.216518,0.358381,25.071183,4.293502,19.724109,0.084742,0.200189,1.270251,0.110730,0.738767,0.534381,0.0,0.21920,0.225700
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000
25%,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.000000
50%,12.000000,0.000000,2.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.0,0.00000,0.000000
75%,18.000000,0.000000,2.000000,0.000000,0.000000,0.000000,18.000000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.0,0.00000,0.000000
max,31.000000,1.000000,4.000000,1.000000,1.000000,1.000000,728.000000,253.000000,186.000000,1.000000,1.000000,14.000000,3.000000,4.000000,3.000000,0.0,1.00000,1.000000

In [5]:
#Distribution de la cible
print(df["is_malicious"].value_counts())

is_malicious
0    112228
1      6386
Name: count, dtype: int64

In [6]:
#Valeurs manquantes
print(df.isnull().sum())

employee_department            0
employee_campus                0
employee_position              0
employee_seniority_years       0
is_contractor                  0
employee_classification        0
has_foreign_citizenship        0
has_criminal_record            0
has_medical_history            0
employee_origin_country        0
total_printed_pages            0
num_printed_pages_off_hours    0
total_files_burned             0
burned_from_other              0
is_abroad                      0
trip_day_number                0
hostility_country_level        0
num_entries                    0
num_unique_campus              0
late_exit_flag                 0
entry_during_weekend           0
is_malicious                   0
dtype: int64

In [7]:
#Corrélation avec la cible
corr = df.select_dtypes(include="number").corr()["is_malicious"].drop("is_malicious")

print(corr.sort_values(ascending=False))
print()
print(df['late_exit_flag'].value_counts())

total_files_burned             0.423465
burned_from_other              0.297451
num_printed_pages_off_hours    0.196895
total_printed_pages            0.156477
num_unique_campus              0.122642
hostility_country_level        0.109457
entry_during_weekend           0.105110
num_entries                    0.101549
employee_classification        0.049519
employee_seniority_years       0.045448
has_foreign_citizenship        0.020623
is_abroad                      0.016589
trip_day_number                0.013862
has_medical_history            0.008291
is_contractor                 -0.029547
has_criminal_record           -0.034660
late_exit_flag                      NaN
Name: is_malicious, dtype: float64

late_exit_flag
0    118614
Name: count, dtype: int64

In [8]:
#Valeurs uniques
for col in ["employee_department","employee_campus","employee_position","employee_origin_country"]:
    print(col, ":", df[col].nunique(), "valeurs uniques")

employee_department : 11 valeurs uniques
employee_campus : 3 valeurs uniques
employee_position : 48 valeurs uniques
employee_origin_country : 32 valeurs uniques